"""Canonical identity, complete provenance, and determinism.

A replay record that cannot be regenerated byte-for-byte is not a replay
record. Three things have to hold for that: one serialization per artifact, a
digest that actually is a digest, and provenance complete enough that the
decision can be re-checked from the stored record alone rather than from a
registry that vanished when the process exited.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pydantic
import pytest

import helpers_discharge
from rh_research_engine.contracts.discharge import resolve_discharges
from rh_research_engine.contracts.hashing import (
    HashFormatError,
    canonical_hash,
    canonical_json,
    validate_sha256,
)
from rh_research_engine.contracts.receipts import DreReceipt, ReceiptAuthentication
from rh_research_engine.properties.closure import implication_closure
from rh_research_engine.properties.models import (
    ClosureMode,
    EpistemicStatus,
    MathematicalRole,
    PropertyGraph,
    PropertyKind,
    PropertyRecord,
    Provenance,
)

REPO = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# 8.1  Canonical identity
# ---------------------------------------------------------------------------


def test_canonical_json_is_order_independent():
    """Key order is the commonest source of a digest that will not reproduce."""
    assert canonical_json({"b": 1, "a": 2}) == canonical_json({"a": 2, "b": 1})
    assert canonical_hash({"b": 1, "a": 2}) == canonical_hash({"a": 2, "b": 1})


def test_canonical_json_leaves_no_whitespace_to_drift():
    assert canonical_json({"a": 1, "b": [1, 2]}) == '{"a":1,"b":[1,2]}'


def test_canonical_json_keeps_mathematical_notation_as_itself():
    """`ensure_ascii=False`: escape spellings vary between encoders."""
    assert canonical_json({"k": "θ <= 1/2"}) == '{"k":"θ <= 1/2"}'


def test_a_receipt_hash_is_canonical_json_not_concatenation():
    """Joining fields with a delimiter is ambiguous and positional.

    A field containing the delimiter shifts the boundary, so two different
    receipts can produce one string; and adding a field silently redefines the
    digest without changing its shape.
    """
    _, _, decisions, receipts = helpers_discharge.accepted_registry()
    receipt = receipts["DEC-1"]
    assert receipt.receipt_hash() == canonical_hash(receipt.model_dump(mode="json"))
    assert receipt.receipt_hash() == receipt.model_copy().receipt_hash()

    # Changing any field changes the identity.
    altered = receipt.model_copy(update={"dre_input_hash": "f" * 64})
    assert altered.receipt_hash() != receipt.receipt_hash()
    assert decisions  # the registry is wired up; not an empty-input pass


@pytest.mark.parametrize(
    "field",
    ["dre_decision_hash", "dre_input_hash", "dre_model_pack_hash", "dre_proof_hash"],
)
@pytest.mark.parametrize(
    "bad", ["", "pending", "A" * 64, "a" * 63, "a" * 65, "g" * 64], ids=range(6)
)
def test_a_hash_field_must_hold_a_hash(field, bad):
    """Uppercase is rejected rather than normalized.

    Two spellings of one digest is two identities for one artifact, and the
    comparison that matters is done on the raw string.
    """
    fields = dict(
        decision_ref="DEC-1",
        dre_decision_hash="a" * 64,
        dre_input_hash="b" * 64,
        dre_model_pack_hash="c" * 64,
        dre_engine_fingerprint="engine@1",
        dre_proof_hash="d" * 64,
    )
    fields[field] = bad
    with pytest.raises(pydantic.ValidationError, match="64 lowercase hexadecimal"):
        DreReceipt(**fields)


def test_the_bound_hashes_on_a_decision_are_validated_too():
    from rh_research_engine.contracts.artifacts import (
        DreDecisionStatus,
        ObligationDischargeDecision,
    )

    with pytest.raises(pydantic.ValidationError, match="evidence_hashes\\[1\\]"):
        ObligationDischargeDecision(
            artifact_id="DEC-1",
            created_by="dre",
            method_family="dre",
            method_version="0.22.0",
            obligation_ref="OBL-1",
            obligation_hash="a" * 64,
            evidence_refs=["EV-1", "EV-2"],
            evidence_hashes=["b" * 64, "not-a-hash"],
            discharged_direction="A => RH",
            dre_decision_ref="run-1",
            dre_decision_status=DreDecisionStatus.PENDING,
            dre_pack_version="0.1.0",
        )


def test_the_hash_validator_names_the_field_it_rejected():
    """"Invalid input" sends a reader looking at the value, not the field."""
    with pytest.raises(HashFormatError, match="DreReceipt.dre_proof_hash"):
        validate_sha256("nope", "DreReceipt.dre_proof_hash")


# ---------------------------------------------------------------------------
# 8.2  Complete provenance
# ---------------------------------------------------------------------------

#: Everything a reader needs to re-check a discharge without the registries.
REQUIRED_PROVENANCE_FIELDS = {
    "obligation_ref",
    "obligation_hash",
    "evidence_refs",
    "evidence_hashes",
    "discharged_direction",
    "requirements_satisfied",
    "decision_ref",
    "decision_hash",
    "receipt_ref",
    "receipt_hash",
    "dre_engine_fingerprint",
    "dre_model_pack_hash",
    "dre_input_hash",
    "dre_proof_hash",
    "receipt_authentication",
}


def _accepted_resolution():
    obligations, evidence, decisions, receipts = helpers_discharge.accepted_registry()
    with helpers_discharge.trusting_test_engine(receipts.values()):
        return resolve_discharges(
            ["OBL-1"],
            obligations=obligations,
            evidence=evidence,
            decisions=decisions,
            receipts=receipts,
        )


def test_a_qualifying_discharge_carries_its_full_replay_identity():
    resolution = _accepted_resolution()
    assert resolution.qualifying == ["OBL-1"]
    payload = resolution.provenance_payload()["OBL-1"]
    assert set(payload) == REQUIRED_PROVENANCE_FIELDS
    assert payload["dre_engine_fingerprint"] == helpers_discharge.TEST_ENGINE
    assert payload["receipt_authentication"] == "signature"


def test_a_refused_discharge_carries_no_provenance():
    """Provenance is evidence of authority, so it exists only where authority does."""
    resolution = resolve_discharges(
        ["OBL-1"], **dict(zip(
            ("obligations", "evidence", "decisions", "receipts"),
            helpers_discharge.accepted_registry(),
            strict=True,
        ))
    )
    assert resolution.qualifying == []
    assert resolution.provenance_payload() == {}


def _circular_premise() -> PropertyRecord:
    return PropertyRecord(
        id="P-EQ",
        object_id="obj",
        kind=PropertyKind.GROWTH_BOUND,
        value="X^0.4",
        status=EpistemicStatus.KNOWN,
        provenance=[Provenance(source_type="knowledge", source_id="K", method="m")],
        role=MathematicalRole.EQUIVALENCE,
        rh_equivalent=True,
        discharged_obligations=["OBL-1"],
    )


def test_closure_persists_the_discharge_provenance_into_the_graph():
    """Held only in the caller's registries, none of this survives the run.

    A reader of the stored graph would otherwise see a rigorous derived bound
    whose premise restates RH, with nothing recording why that was allowed.
    """
    obligations, evidence, decisions, receipts = helpers_discharge.accepted_registry()
    with helpers_discharge.trusting_test_engine(receipts.values()):
        graph = implication_closure(
            PropertyGraph(properties=[_circular_premise()]),
            mode=ClosureMode.RIGOROUS,
            obligations=obligations,
            evidence=evidence,
            decisions=decisions,
            receipts=receipts,
        )
    derived = [p for p in graph.properties if p.id != "P-EQ"]
    assert derived, "the discharge should have unlocked the rule"
    provenance = derived[0].metadata["discharge_provenance"]["OBL-1"]
    assert set(provenance) == REQUIRED_PROVENANCE_FIELDS
    assert derived[0].metadata["premise_hash"] == _circular_premise().record_hash()

    # And it survives serialization: a transient registry is not provenance.
    round_tripped = json.loads(json.dumps(graph.model_dump(mode="json")))
    stored = [p for p in round_tripped["properties"] if p["id"] != "P-EQ"][0]
    assert set(stored["metadata"]["discharge_provenance"]["OBL-1"]) == (
        REQUIRED_PROVENANCE_FIELDS
    )


# ---------------------------------------------------------------------------
# 8.3  Metadata is annotation, never authority
# ---------------------------------------------------------------------------


def test_metadata_is_outside_the_artifact_identity():
    """A value the identity does not cover can be edited without changing it."""
    from rh_research_engine.contracts.artifacts import PropertyAssertion

    base = dict(
        artifact_id="A-1",
        created_by="rh-math-worker",
        method_family="python",
        method_version="0.11.0",
        object_id="obj",
        property_kind="bound",
        value="X^0.4",
    )
    plain = PropertyAssertion(**base)
    annotated = PropertyAssertion(**base, metadata={"reviewed_by": "someone"})
    assert plain.artifact_hash() == annotated.artifact_hash()
    assert "metadata" not in json.loads(plain.canonical_json())


def test_a_favourable_verdict_written_into_metadata_changes_nothing():
    """Closure re-resolves every run; there is no cached verdict to poison."""
    premise = _circular_premise().model_copy(
        update={"metadata": {"advances_frontier": True, "discharge_receipts": {"OBL-1": "x"}}}
    )
    graph = implication_closure(
        PropertyGraph(properties=[premise]), mode=ClosureMode.RIGOROUS
    )
    assert [p.id for p in graph.properties] == ["P-EQ"]


# ---------------------------------------------------------------------------
# 3.4  EXPLORATORY relaxes rigour, never circularity
# ---------------------------------------------------------------------------


def test_exploratory_mode_relaxes_rigour():
    """A non-rigorous premise may drive a heuristic conclusion."""
    premise = PropertyRecord(
        id="P-SOFT",
        object_id="obj",
        kind=PropertyKind.GROWTH_BOUND,
        value="X^0.4",
        status=EpistemicStatus.SYMBOLIC_DERIVED,
        provenance=[Provenance(source_type="symbolic", source_id="s", method="m")],
        role=MathematicalRole.BOUND,
    )
    rigorous = implication_closure(
        PropertyGraph(properties=[premise]), mode=ClosureMode.RIGOROUS
    )
    exploratory = implication_closure(
        PropertyGraph(properties=[premise]), mode=ClosureMode.EXPLORATORY
    )
    assert [p.id for p in rigorous.properties] == ["P-SOFT"]
    derived = [p for p in exploratory.properties if p.id != "P-SOFT"]
    assert derived, "exploratory mode should relax the rigour requirement"
    assert derived[0].status is EpistemicStatus.HEURISTIC


def test_exploratory_mode_does_not_relax_circularity():
    """The relaxation is on confidence only.

    An undischarged RH-equivalent premise is not `frontier_relevant`, and
    exploratory mode still requires that. Otherwise the mode intended for
    loosening rigour would quietly re-enable the circular step the whole layer
    exists to block.
    """
    graph = implication_closure(
        PropertyGraph(properties=[_circular_premise()]), mode=ClosureMode.EXPLORATORY
    )
    assert [p.id for p in graph.properties] == ["P-EQ"]


# ---------------------------------------------------------------------------
# 8.4  Determinism across processes and hash seeds
# ---------------------------------------------------------------------------

_HASH_SCRIPT = """
import json, sys
sys.path.insert(0, %r)
sys.path.insert(0, %r)
from helpers_discharge import accepted_registry
obligations, evidence, decisions, receipts = accepted_registry()
print(json.dumps({
    "obligation": obligations["OBL-1"].artifact_hash(),
    "evidence": evidence["EV-1"].artifact_hash(),
    "decision": decisions["OBL-1"].artifact_hash(),
    "receipt": receipts["DEC-1"].receipt_hash(),
}))
"""


@pytest.mark.parametrize("seed", ["0", "1", "12345"])
def test_artifact_identity_is_independent_of_the_hash_seed(seed):
    """Set and dict iteration order is seeded per interpreter.

    In-process tests cannot catch anything seeded that way, because they all
    share one interpreter. Separate invocations under different seeds can.
    """
    script = _HASH_SCRIPT % (str(REPO / "src"), str(REPO / "tests"))
    result = subprocess.run(
        [sys.executable, "-c", script],
        capture_output=True,
        text=True,
        encoding="utf-8",
        env={"PYTHONHASHSEED": seed, "PATH": "", "SYSTEMROOT": ""},
    )
    assert result.returncode == 0, result.stderr
    hashes = json.loads(result.stdout)
    assert hashes == {
        "obligation": hashes["obligation"],
        "evidence": hashes["evidence"],
        "decision": hashes["decision"],
        "receipt": hashes["receipt"],
    }
    # Compare against the in-process values, which is the actual invariant.
    obligations, evidence, decisions, receipts = helpers_discharge.accepted_registry()
    assert hashes["obligation"] == obligations["OBL-1"].artifact_hash()
    assert hashes["evidence"] == evidence["EV-1"].artifact_hash()
    assert hashes["decision"] == decisions["OBL-1"].artifact_hash()
    assert hashes["receipt"] == receipts["DEC-1"].receipt_hash()


def test_the_same_inputs_produce_the_same_closure_output():
    """Two runs over identical inputs must agree on every byte."""
    obligations, evidence, decisions, receipts = helpers_discharge.accepted_registry()
    outputs = []
    for _ in range(2):
        with helpers_discharge.trusting_test_engine(receipts.values()):
            outputs.append(
                implication_closure(
                    PropertyGraph(properties=[_circular_premise()]),
                    mode=ClosureMode.RIGOROUS,
                    obligations=obligations,
                    evidence=evidence,
                    decisions=decisions,
                    receipts=receipts,
                ).graph_hash()
            )
    assert outputs[0] == outputs[1]


def test_an_unauthenticated_receipt_is_refused_even_from_a_trusted_engine():
    """The activation requirement, enforced rather than documented.

    A fingerprint names the *claimed* issuer, and the claim travels inside the
    receipt. Registering one is necessary and not sufficient.
    """
    registry = helpers_discharge.unauthenticated_receipt_registry()
    with helpers_discharge.trusting_registry(registry):
        resolution = resolve_discharges(
            ["OBL-1"], **dict(zip(
                ("obligations", "evidence", "decisions", "receipts"),
                registry,
                strict=True,
            ))
        )
    assert resolution.qualifying == []
    assert "receipt_authentication" in resolution.explain()
    assert ReceiptAuthentication.NONE.value in resolution.explain()
