from __future__ import annotations

from pathlib import Path

from ..core.models import EvidenceClass
from .contracts import DreEvidenceEnvelope

#: Reliability ceiling declared in the pack policy as `high_reliability`.
HIGH_RELIABILITY = 1000

#: Reliability by evidence class. Non-deductive evidence is deliberately kept
#: below the ceiling: stamping a fitted exponent at the same reliability as a
#: symbolic derivation is how a diagnostic becomes a decision.
_RELIABILITY = {
    EvidenceClass.HEURISTIC: 300,
    EvidenceClass.NUMERICAL: 500,
    EvidenceClass.RIGOROUS_NUMERICAL: 700,
    EvidenceClass.COUNTEREXAMPLE: 900,
    EvidenceClass.SYMBOLIC: 900,
}


def reliability_for(evidence_class: EvidenceClass) -> int:
    return _RELIABILITY.get(evidence_class, HIGH_RELIABILITY)


def _scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = str(value)
    if text and all(ch.isalnum() or ch in "-_.:/" for ch in text):
        return text
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _evidence(eid: str, predicate: str, value: object, reliability: int, observed_at: int) -> list[str]:
    return [
        f"      - id: {eid}",
        "        subject: run",
        f"        predicate: {predicate}",
        f"        value: {_scalar(value)}",
        "        source: rh-math-worker",
        f"        reliability: {reliability}",
        f"        observed_at: {observed_at}",
    ]


def render_dre_experiment(
    envelope: DreEvidenceEnvelope,
    *,
    experiment_id: str | None = None,
    pack_path: str = "model-packs/riemann-research",
    observed_at: int = 1,
    now: int | None = None,
) -> str:
    """Render a DRE evidence file.

    ``observed_at`` is a *logical* clock -- in practice the run's index in
    ``experiments.jsonl`` -- not wall-clock time. DRE bans ``SystemTime`` from
    its engine crates precisely because decisions must not observe time, so
    threading a real timestamp here would fight the engine's determinism model.
    A monotonic run counter keeps ``freshness_window`` meaningful and replay
    reproducible at the same time.
    """
    if observed_at < 1:
        raise ValueError("observed_at must be a positive logical tick")
    current = observed_at if now is None else now
    if current < observed_at:
        raise ValueError("now must not precede observed_at")
    eid = experiment_id or f"rh-{envelope.experiment_name}-{envelope.payload_hash[:12]}"
    reliability = reliability_for(envelope.evidence_class)
    lines = [
        "# Generated by rh-research-engine. Numerical outputs are evidence, not decisions.",
        "# evidence_class, method_family, and worker_version are worker-declared and are",
        "# not overridable at export time. observed_at is a logical run index, not a clock.",
        "experiment:",
        f"  id: {_scalar(eid)}",
        "  description: >-",
        f"    DRE evidence envelope for RH math-worker experiment {envelope.experiment_name};",
        "    DRE remains authoritative for epistemic status and promotion decisions.",
        f"  pack: {pack_path}",
        "",
        "  given:",
        f"    now: {current}",
        "",
        "    policy:",
        f"      high_reliability: {HIGH_RELIABILITY}",
        "      corroboration_required: 2",
        "      freshness_window: 1000000000",
        "",
        "    sources:",
        "      - id: rh-math-worker",
        f"        reliability: {reliability}",
        f"        independence_group: {_scalar(envelope.independence_group)}",
        "",
        "    evidence:",
    ]
    fields: list[tuple[str, object]] = [
        ("experiment_name", envelope.experiment_name),
        ("claim_id", envelope.claim_id),
        ("claim_effect", envelope.claim_effect.value),
        ("evidence_class", envelope.evidence_class.value),
        ("method_family", envelope.method_family),
        ("worker_version", envelope.worker_version),
        ("payload_hash", envelope.payload_hash),
        ("provenance_hash", envelope.provenance_hash),
        # Assumptions must cross the boundary. A conditional enclosure that
        # arrives as an unconditional predicate is the circular-reasoning
        # primitive: an RH-assuming certificate becoming evidence for RH.
        ("assumption_count", envelope.assumption_count),
        ("assumptions_present", envelope.assumption_count > 0),
        ("rh_equivalent", envelope.rh_equivalent),
        ("counterexample_found", envelope.counterexample_found),
        ("independently_verified", envelope.independently_verified),
    ]
    if envelope.primary_metric_name is not None:
        fields.append(("primary_metric_name", envelope.primary_metric_name))
    if envelope.scaled_primary_metric() is not None:
        fields.append(("primary_metric_scaled", envelope.scaled_primary_metric()))
        fields.append(("primary_metric_scale", envelope.primary_metric_scale))
    if envelope.theta_upper_ppb() is not None:
        fields.append(("theta_upper_ppb", envelope.theta_upper_ppb()))
    if envelope.bound_exponent_ppb() is not None:
        fields.append(("bound_exponent_ppb", envelope.bound_exponent_ppb()))
    for idx, (predicate, value) in enumerate(fields, start=1):
        lines.extend(_evidence(f"E{idx:03d}", predicate, value, reliability, observed_at))

    if envelope.assumptions:
        lines.append("")
        lines.append("    # Assumptions carried by this evidence, verbatim from the worker record.")
        for assumption in sorted(envelope.assumptions):
            lines.append(f"    # - {assumption}")

    lines.extend([
        "",
        "    entities:",
        "      - id: run",
        "        type: research_run",
        "",
        "  expect:",
        "    states_expanded: 0",
        "",
    ])
    return "\n".join(lines)


def write_dre_experiment(envelope: DreEvidenceEnvelope, path: Path, **kwargs: object) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    # newline="" so the bytes are identical on every platform. DRE hashes the
    # raw bytes of a pack, so a CRLF copy of this file is a different model.
    path.write_text(
        render_dre_experiment(envelope, **kwargs), encoding="utf-8", newline=""
    )
    return path
