"""Canonical identity: one serialization, one hash, one hex format.

Every authoritative artifact needs a *deterministic* canonical serialization,
because a replay record that cannot be regenerated byte-for-byte is not a
replay record. Two things were getting in the way.

**Delimiter concatenation is not canonical.** ``DreReceipt.receipt_hash``
joined its fields with ``"|"``. That is ambiguous in the way every ad-hoc
concatenation is: a field containing the delimiter shifts the boundary, so two
different receipts can produce the same string. It is also positional, so
adding a field silently changes the meaning of the digest without changing its
shape. Canonical JSON has neither problem -- keys are sorted, the structure is
explicit, and a new field is visible in the payload.

**A hash field that is not checked is a free-text field.** ``obligation_hash``,
``evidence_hashes`` and the four ``dre_*_hash`` fields are all SHA-256 digests,
and nothing stopped a caller writing ``"pending"`` or ``"see attached"`` into
one. A malformed digest never *matches* anything, so it fails closed -- but it
fails closed with a confusing message about a mismatch rather than a clear one
about a field that was never a hash.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any

#: Exactly 64 lowercase hexadecimal characters. Uppercase is rejected rather
#: than normalized: two spellings of one digest means two identities for one
#: artifact, and the comparison that matters is done on the raw string.
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")


class HashFormatError(ValueError):
    """A field documented as SHA-256 does not hold a SHA-256 digest."""


def canonical_json(payload: Any) -> str:
    """The one serialization used for every artifact identity in this package.

    ``sort_keys`` makes the output independent of insertion order and therefore
    of ``PYTHONHASHSEED``; the compact separators leave no whitespace to drift;
    ``ensure_ascii=False`` keeps mathematical notation as itself rather than as
    escape sequences whose form varies between encoders.
    """
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def canonical_hash(payload: Any) -> str:
    """SHA-256 over :func:`canonical_json`."""
    return hashlib.sha256(canonical_json(payload).encode("utf-8")).hexdigest()


def validate_sha256(value: str, field: str) -> str:
    """Return ``value`` if it is a SHA-256 digest, else raise naming the field."""
    if not isinstance(value, str) or not SHA256_PATTERN.match(value):
        raise HashFormatError(
            f"{field} must be exactly 64 lowercase hexadecimal characters, got "
            f"{value!r}. This field content-addresses an artifact; a value that is "
            "not a digest can never match one, so it would fail later as a spurious "
            "mismatch rather than here as a malformed field."
        )
    return value


def validate_sha256_list(values: list[str], field: str) -> list[str]:
    """Validate every entry, naming the index that failed."""
    return [validate_sha256(value, f"{field}[{index}]") for index, value in enumerate(values)]
